GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "user": "amazing you",
    "title": "react is great",
    "content": "yes, it is",
    "password": "password_1234"
}

###

GET http://localhost:3000/posts/63ac63fdaf5eb6f38e7da874

###
PATCH http://localhost:3000/posts/63ac63fdaf5eb6f38e7da874
Content-Type: application/json

{
    "user": "amazing sparta",
    "password": "password_1234"
}

###
DELETE http://localhost:3000/posts/63ac63fdaf5eb6f38e7da874
Content-Type: application/json

{
    "password": "password_1234"
}

###

GET http://localhost:3000/comments

###

POST http://localhost:3000/comments/63ac2f3e4661551d8e97acca
Content-Type: application/json

{
    "user": "seungyoon",
    "content": "nodejs is the best",
    "password": "password_111"
}

###
GET http://localhost:3000/comments/63ac324081c4e3204978d3f2

###
PATCH http://localhost:3000/comments/63ac31269ed7286af833bc05
Content-Type: application/json

{
    "content": "spring is the best",
    "password": "password_111"
}

###
DELETE http://localhost:3000/comments/63ac31269ed7286af833bc05
Content-Type: application/json

{
    "password": "password_111"
}